### PR TITLE
Added NetStandard 1.4 support

### PR DESCRIPTION
**Pull request by Davidblkx**
Added a Net Standard project so it could be target by .Net Core projects

### CODE REVIEW

**Comment by MathewSachin** [comment]
First of all thank you for your interest to contribute.

Now, this needs to be done for every add-on.
Also, you may have not noticed, but your pull request also adds x86 and x64 configuration to the solution.

**Comment by Davidblkx** [comment]
You're right, visual studio changed the solution without me noticing it. I've already revert it.
Regarding the Add-on implementation I'm planning to do it only when I need it for my project, so it could take a while

**Comment by MathewSachin** [comment]
Hey @Davidblkx, I got some spare time for this and am working on a new pull request #25.
Moving all PCL projects to .Net Standard.

There's still more I have to do.

Would be great if you review if you review it after that.

**Comment by Davidblkx** [comment]
That's good news! Sure, I can review it when you´re done.

**Comment by MathewSachin** [comment]
Closing in favour of #25

**Comment by MathewSachin** [comment]
Hi. I feel like I have done my part. Please review #25

**Pull request closed without merging**
