### PR TITLE
Prepare BASS FX and BASS MIX for usage in Xamarin.iOS

### PR DESCRIPTION
**Pull request by ITDancer13**
Split projects and using *DllName* within each PInvoke-file to support usage in e.g. Xamain.iOS.

### CODE REVIEW

**Comment by MathewSachin** [comment]
We used to have different projects for Xamarin.iOS for BASS FX and BASS MIX.
That was changed in this commit: https://github.com/ManagedBass/ManagedBass/commit/a35316b98abbd809e70298ddfb398905a4932425

Now, you can just use DllMap like in this file: https://github.com/ManagedBass/ManagedBass/blob/master/src/app.config
Did it not work for you?

**Comment by ITDancer13** [comment]
Unfortunately not (at least with the latest package from NuGet). I got runtime dll-load exceptions, telling me that my iOS tried to load 'bassmix' / 'bass_fx' dll. With this changes it works fine for me.

**Comment by MathewSachin** [comment]
Can you check the workaround on this issue: https://github.com/ManagedBass/ManagedBass/issues/76
Renaming app.config to ManagedBass.Fx.dll.config
Unfortunately, I don't have an iPhone to test this.

**Comment by ITDancer13** [comment]
Yeah I saw this comment a few days ago, when I first tried to get it running but it didn't work. Maybe I did something wrong as it's my first native iOS lib in Xamarin. 

Your ManagedBass lib worked out of the box without any additional changes. So I tried it the same way in my fork and it worked without any additional change (I just had to add the mtouch arguments as described in un4seen forum _-gcc_flags "-lstdc++"_).

**Comment by MathewSachin** [comment]
> Renaming the app.config to ManagedBass.Fx.dll.config and setting the build action to BundleResource worked for me.

From the linked Xamarin issue, you also need to set Build Action to BundleResource.

**Comment by ITDancer13** [comment]
Crazy, I tried it on an empty project and the it works. So I think I have an issue in my bigger solution. 

I'll cancel this PR but maybe I can create a separate one to add it a description how to get it running to Readme.md if you like it?

**Comment by MathewSachin** [comment]
>  I can create a separate one to add it a description how to get it running to Readme.md if you like it

Sure, that would be nice 👍

**Pull request closed without merging**
